#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Shop_Store.LinkFile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Smart-Shop-Store")]
	public partial class LinkToSQLContextClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    #endregion
		
		public LinkToSQLContextClassDataContext() : 
				base(global::Smart_Shop_Store.Properties.Settings.Default.Smart_Shop_StoreConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinkToSQLContextClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinkToSQLContextClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinkToSQLContextClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinkToSQLContextClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectAllProducts")]
		public ISingleResult<SelectAllProductsResult> SelectAllProducts()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelectAllProductsResult>)(result.ReturnValue));
		}
	}
	
	public partial class SelectAllProductsResult
	{
		
		private System.Guid _IdProduit;
		
		private string _NomProduit;
		
		private double _PrixProduit;
		
		private System.Nullable<int> _Stock;
		
		private bool _ImageProduit;
		
		private System.Nullable<bool> _Promo;
		
		private string _Marque;
		
		public SelectAllProductsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProduit", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IdProduit
		{
			get
			{
				return this._IdProduit;
			}
			set
			{
				if ((this._IdProduit != value))
				{
					this._IdProduit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomProduit", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NomProduit
		{
			get
			{
				return this._NomProduit;
			}
			set
			{
				if ((this._NomProduit != value))
				{
					this._NomProduit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrixProduit", DbType="Float NOT NULL")]
		public double PrixProduit
		{
			get
			{
				return this._PrixProduit;
			}
			set
			{
				if ((this._PrixProduit != value))
				{
					this._PrixProduit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this._Stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageProduit", DbType="Bit NOT NULL")]
		public bool ImageProduit
		{
			get
			{
				return this._ImageProduit;
			}
			set
			{
				if ((this._ImageProduit != value))
				{
					this._ImageProduit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promo", DbType="Bit")]
		public System.Nullable<bool> Promo
		{
			get
			{
				return this._Promo;
			}
			set
			{
				if ((this._Promo != value))
				{
					this._Promo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marque", DbType="NVarChar(50)")]
		public string Marque
		{
			get
			{
				return this._Marque;
			}
			set
			{
				if ((this._Marque != value))
				{
					this._Marque = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
